version: '3'

services:
    
    nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./src/sharkdata_py3:/sharkdata_py3
        - ./config/nginx:/etc/nginx/conf.d
        - ./static:/static
      depends_on:
        - django

    django:
      build: .
      env_file:
        - sharkdata_py3.env
      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn sharkdata_py3.wsgi -b 0.0.0.0:8000"
      volumes:
        - ./src/sharkdata_py3:/sharkdata_py3
        - ./static:/static
        - ./db:/db
        - ./data:/data
        - ./data_in:/data_in
      expose:
        - "8000"
