version: '3'

services:
    
    nginx:
      image: nginx:latest
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./config/nginx:/etc/nginx/conf.d
        - ./static:/static
      depends_on:
        - django

    django:
      build: .
      restart: always
      env_file:
        - sharkdata.env
      command: >
        sh -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn sharkdata_py3.wsgi -b 0.0.0.0:8000"
      volumes:
        - ./static:/static
        - ./db:/db
        - ./data:/data
        - ./data_in:/data_in
      expose:
        - "8000"

