version: '3'

services:
    
    nginx:
      image: nginx:latest
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./config/nginx:/etc/nginx/conf.d
        - static:/static
      depends_on:
        - django

    sftp:
      image: atmoz/sftp
      ports:
        - "2222:22"
      env_file:
        - sharkdata.env
      volumes:
        - datasets:/datasets
        - resources:/resources

    django:
      build: .
      restart: always
      env_file:
        - sharkdata.env
      command: >
        sh -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn sharkdata_py3.wsgi -b 0.0.0.0:8000"
      volumes:
        - static:/static
        - log:/log
        - db:/db
        - data:/data
        - datasets:/data_in/datasets
        - resources:/data_in/resources
      expose:
        - "8000"

volumes:
  static:
  log:
  db:
  data:
  datasets:
  resources:
